name: "Bump version"
description: "Bump version of PR"
inputs:
  GITHUB_TOKEN:
    description: 'Github token'
    required: true
    default: '${{ github.token }}'
runs:
  using: "docker"
  image: 'Dockerfile'