
on:
  - pull_request

jobs:
    build:
        name: Bump versoin of PR
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Bump version of PR
              uses: ./
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
