
on:
  push:
    branches:
      - uat

jobs:
    build:
        name: Bump versoin of PR
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Comment a pull_request
              uses: ./
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
